### ISSUE TITLE
Make RMP Search more strict

### ISSUE THREAD

**Issue by Kanishk-K** [samyok/gophergrades#117] opened 2024-03-03 18:58 UTC
We've received reports that the RMP connections provided are not always correct. This could be prevented by adding a validation step that verifies that the professors belong to one of the UMN-affiliated campus codes. It is more beneficial to have a false negative (where a professor is NOT found when they do exist on RMP) as opposed to a false positive (when a professor is found but is not on RMP).

**Comment by adam-douiri** [comment] 2024-03-31 23:01
The code in data-app/gen_rmp.py should already throw an exception if the professor isn't at the University of Minnesota, as on line 10 the professor is fetched using both school and name. I tried to replicate the issue using Maru Sarazola, who does have a separate RMP profile for a different university, but not a UMN RMP profile. It appears Sarazola's RMP label doesn't appear as intended. Is there any specific examples of professors who's RMP connection isn't correct?

**Comment by samyok** [comment] 2024-04-25 05:21
Fixed by #121

**Closed by samyok** 2024-04-25 05:21 UTC
Labels: bug, good first issue, backend
